### ISSUE TITLE
Auto loading stats on launch does not work

### ISSUE THREAD

**Issue by UlyssesZh** [RoanH/KeysPerSecond#92]
Auto loading stats on launch does not work. I can, however, load stats manually after it launches.

Relevant part of the config file:
```yaml
statsSaving:
  autoSave: true
  autoDestination: /home/ulysses/data/KeysPerSecond/stats
  autoFormat: 'md.kpsstats'
  autoInterval: 1000
  saveOnExit: true
  loadOnLaunch: true
  saveFile: /home/ulysses/data/KeysPerSecond/stats/md.kpsstats
```

Tested on Linux with KPS 8.8.
